name: python-programming
channels:
    - defaults
    - conda-forge
dependencies:
    - python
    - numpy
    - pip
    - pip:
        - pandas
        - matplotlib
        - numpy
        - scipy
        - sklearn

